// <auto-generated />
using System;
using Kolokwium2GrupaA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kolokwium2GrupaA.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250608130344_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kolokwium2GrupaA.Models.AvailableProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProgramWId")
                        .HasColumnType("int");

                    b.Property<int>("WashingMashineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProgramWId");

                    b.HasIndex("WashingMashineId");

                    b.ToTable("AvailablePrograms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 2.3999999999999999,
                            ProgramWId = 1,
                            WashingMashineId = 1
                        },
                        new
                        {
                            Id = 2,
                            Price = 2.3999999999999999,
                            ProgramWId = 2,
                            WashingMashineId = 2
                        },
                        new
                        {
                            Id = 3,
                            Price = 2.3999999999999999,
                            ProgramWId = 3,
                            WashingMashineId = 3
                        });
                });

            modelBuilder.Entity("Kolokwium2GrupaA.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "John",
                            LastName = "Doe",
                            PhoneNumber = "08888888888"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Jane",
                            LastName = "Doe",
                            PhoneNumber = "08888888888"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Julie",
                            LastName = "Doe",
                            PhoneNumber = "null"
                        });
                });

            modelBuilder.Entity("Kolokwium2GrupaA.Models.ProgramW", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemperatureCelsius")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProgramW");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DurationMinutes = 4,
                            Name = "Program1",
                            TemperatureCelsius = 3
                        },
                        new
                        {
                            Id = 2,
                            DurationMinutes = 4,
                            Name = "Program2",
                            TemperatureCelsius = 3
                        },
                        new
                        {
                            Id = 3,
                            DurationMinutes = 4,
                            Name = "Program3",
                            TemperatureCelsius = 3
                        });
                });

            modelBuilder.Entity("Kolokwium2GrupaA.Models.PurchaseHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableProgramId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AvailableProgramId");

                    b.HasIndex("CustomerId");

                    b.ToTable("PurchaseHistory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableProgramId = 1,
                            CustomerId = 1,
                            PurchaseDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3
                        },
                        new
                        {
                            Id = 2,
                            AvailableProgramId = 2,
                            CustomerId = 2,
                            PurchaseDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3
                        },
                        new
                        {
                            Id = 3,
                            AvailableProgramId = 3,
                            CustomerId = 3,
                            PurchaseDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3
                        });
                });

            modelBuilder.Entity("Kolokwium2GrupaA.Models.WashingMachine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("MaxWeight")
                        .HasColumnType("float");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WashingMachine");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxWeight = 2.5,
                            SerialNumber = "AB2"
                        },
                        new
                        {
                            Id = 2,
                            MaxWeight = 1.5,
                            SerialNumber = "AB3"
                        },
                        new
                        {
                            Id = 3,
                            MaxWeight = 3.5,
                            SerialNumber = "AB1"
                        });
                });

            modelBuilder.Entity("Kolokwium2GrupaA.Models.AvailableProgram", b =>
                {
                    b.HasOne("Kolokwium2GrupaA.Models.ProgramW", "ProgramW")
                        .WithMany("Programs")
                        .HasForeignKey("ProgramWId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolokwium2GrupaA.Models.WashingMachine", "WashingMachine")
                        .WithMany("Programs")
                        .HasForeignKey("WashingMashineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramW");

                    b.Navigation("WashingMachine");
                });

            modelBuilder.Entity("Kolokwium2GrupaA.Models.PurchaseHistory", b =>
                {
                    b.HasOne("Kolokwium2GrupaA.Models.AvailableProgram", "AvailableProgram")
                        .WithMany("PurchaseHistory")
                        .HasForeignKey("AvailableProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolokwium2GrupaA.Models.Customer", "Customer")
                        .WithMany("PurchaseHistory")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvailableProgram");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Kolokwium2GrupaA.Models.AvailableProgram", b =>
                {
                    b.Navigation("PurchaseHistory");
                });

            modelBuilder.Entity("Kolokwium2GrupaA.Models.Customer", b =>
                {
                    b.Navigation("PurchaseHistory");
                });

            modelBuilder.Entity("Kolokwium2GrupaA.Models.ProgramW", b =>
                {
                    b.Navigation("Programs");
                });

            modelBuilder.Entity("Kolokwium2GrupaA.Models.WashingMachine", b =>
                {
                    b.Navigation("Programs");
                });
#pragma warning restore 612, 618
        }
    }
}
